---
title: "Meeting"
author: "M. Rolland"
date: "10/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Present: BOU, MR

Agenda:

* Status update
* Different steps + timeline of developing the site
* Site "layout/map"?
* How can I help: what and when?
* Confirm weekly meet
* Do we have a platform name? Domain name?

Done since last time:

* static mockup of the site based on hotosm (https://trello.com/c/Er5IYSPm/12-create-mockup)

Meeting notes:

* Link with github should be straight forward check https://developer.github.com/v3/issues/#create-an-issue  
* Need to define how we will go about authorizing who can create a task: everyone, manually... 
* Need to discuss about data storage: there will be at some point some data not on github that will have to be stored somewhere (AWS, Rstudio...) can temporarily be dealt with google sheets
* Ok for weekly meetings on Friday with reminder on wednesday

To do:

* By next week Ben should have done the architecture and link with github
* Matt: 
  * Some questions for Thibaut
    * Data base? (re notes)
    * Do we have a platform/domain name?
    * Who will write the platform content? (about, help, etc.)
    * Double check the specifications
  * Suggest names for the platform (should have available domain)
  * Get very familiar with hotosm and list what is useful/not for is
