---
title: "Communication"
author: "M. Rolland"
date: "10/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To do:

* tutorial (video + text)?
* ask other member to complete once this is more advanced

Thibaut:

* focus on covid-19 ou bien préciser que ça vaut pour la suite aussi? (car covid-19 bientôt fini)
* sections for task type: developer/public health

Notes meet thibaut 26/11/2020

* EAN: aymerich paytoo
* EAN board
* Epicentre
* accentuer le besoin d'analyse de données epi
* 

To do:

* finish submitting sam's tasks
* write message for the R community
* write message for the public health community
* prepare twitter post

# Social media

* twitter (Matthieu)
  * create account
* facebook (Matthieu)
  * create page
* linkedin (Matthieu)

Hashtags: #rstats #recon

# R developers

"become part of the worldwide response to COVID-19"

* r-bloggers (Matthieu)
* local r user groups/RUGS (France Matthieu)
* r-ladies (Matthieu)
* ropensci (Matthieu)
* data kind (Matthieu)
* stats without borders (Matthieu)
* useR (Matthieu)
* eRum (Matthieu)

# Field epis

* French FETP alumni (Matthieu)
* Isped + Alima (Matthieu)
* Epicentre? (Matthieu)
* Epiet (Matthieu)
* J. Larmarange

# Conferences

* useR
* eRum
* field epi confs?

