---
title: "Infectious diseases epidemiology"
subtitle: "CRAN task view"
author: "M. Rolland"
date: "16/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Short name: InfectiousEpidemiology
  
Short description: Infectious diseases epidemiology

Maintainer:	Thibaut Jombart 
Contact:	mj.rolland at gmail.com  
Version:	  
URL:	

Professionals working in the field of infectious diseases epidemiology (field epidemiologists, researchers, statisticians, mathematical modellers, etc) are increasingly attracted to R because epidemiology is a data driven science for which R provides all the tools necessary to cover the different aspects of an epidemiological study: study design, data exploration, data analysis, modelling and forecasting. It also offers flexibility and a wide array of base functionalities to apply all kinds of field transverse statistical approaches from data visualisation to regression modelling. This task view focuses on packages specific to infectious diseases epidemiology. It does not encompass other applications of epidemiology (such as environmental epidemiology) or transverse methods such as linear regression as previously mentioned. The different packages were regrouped in the following categories: **general purpose** packages aimed at professionals or students of infectious epidemiology, which provide all kinds of functions and helpers for the different steps of an epidemiological study; packages specific to **study design**; packages for epidemiological **data exploration and visualisation**; packages for epidemiological **data analysis, modeling and forecasting** with many different methods and cases; finally packages related to the **COVID-19** epidemiological response.

# General purpose

* [epitools](https://cran.r-project.org/web/packages/epitools/index.html): Tools for training and practicing epidemiologists including methods for two-way and multi-way contingency tables.  
* [epitrix](https://cran.r-project.org/web/packages/epitrix/index.html): A collection of small functions useful for epidemics analysis and infectious disease modelling. This includes computation of basic reproduction numbers from growth rates, generation of hashed labels to anonymise data, and fitting discretised Gamma distributions.  
* [mStats](https://cran.r-project.org/web/packages/mStats/index.html): This is a tool for epidemiologist, medical data analyst, medical or public health professionals. It contains three domains of functions: 1) data management, 2) statistical analysis and 3) calculating epidemiological measures.  
* [pubh](https://cran.r-project.org/web/packages/pubh/index.html): A toolbox for making R functions and capabilities more accessible to students and professionals from Epidemiology and Public Health related disciplines. Includes a function to report coefficients and confidence intervals from models using robust standard errors (when available), functions that expand 'ggplot2' plots and functions relevant for introductory papers in Epidemiology or Public Health. Please note that use of the provided data sets is for educational purposes only.  
* [epiR](https://cran.r-project.org/web/packages/epiR/index.html): Tools for the analysis of epidemiological and surveillance data. Contains functions for directly and indirectly adjusting measures of disease frequency, quantifying measures of association on the basis of single or multiple strata of count data presented in a contingency table, computation of confidence intervals around incidence risk and incidence rate estimates and sample size calculations for cross-sectional, case-control and cohort studies. Surveillance tools include functions to calculate an appropriate sample size for 1- and 2-stage representative freedom surveys, functions to estimate surveillance system sensitivity and functions to support scenario tree modelling analyses.   
* [Epi](https://cran.r-project.org/web/packages/Epi/index.html): Functions for demographic and epidemiological analysis in the Lexis diagram, i.e. register and cohort follow-up data, in particular representation, manipulation and simulation of multistate data - the Lexis suite of functions, which includes interfaces to 'mstate', 'etm' and 'cmprsk' packages. Also contains functions for Age-Period-Cohort and Lee-Carter modeling and a function for interval censored data and some useful functions for tabulation and plotting, as well as a number of epidemiological data sets.  
* [epibasix](https://cran.r-project.org/web/packages/epibasix/index.html): Contains elementary tools for analysis of common epidemiological problems, ranging from sample size estimation, through 2x2 contingency table analysis and basic measures of agreement (kappa, sensitivity/specificity). Appropriate print and summary statements are also written to facilitate interpretation wherever possible. The target audience includes advanced undergraduate and graduate students in epidemiology or biostatistics courses, and clinical researchers.  

# Epidemiological study design

* [powerSurvEpi](https://cran.r-project.org/web/packages/powerSurvEpi/index.html): Functions to calculate power and sample size for testing main effect or interaction effect in the survival analysis of epidemiological studies (non-randomized studies), taking into account the correlation between the covariate of the interest and other covariates. Some calculations also take into account the competing risks and stratified analysis. This package also includes a set of functions to calculate power and sample size for testing main effect in the survival analysis of randomized clinical trials.  

# Epidemiological data visualisation and exploration

* [epiDisplay](https://cran.r-project.org/web/packages/epiDisplay/index.html): Package for data exploration and result presentation.  
* [EpiCurve](https://cran.r-project.org/web/packages/EpiCurve/index.html): Creates simple or stacked epidemic curves for hourly, daily, weekly or monthly outcome data.  
* [EpiReport](https://cran.r-project.org/web/packages/EpiReport/index.html): Drafting an epidemiological report in 'Microsoft Word' format for a given disease, similar to the Annual Epidemiological Reports published by the European Centre for Disease Prevention and Control. Through standalone functions, it is specifically designed to generate each disease specific output presented in these reports and includes: - Table with the distribution of cases by Member State over the last five years; - Seasonality plot with the distribution of cases at the European Union / European Economic Area level, by month, over the past five years; - Trend plot with the trend and number of cases at the European Union / European Economic Area level, by month, over the past five years; - Age and gender bar graph with the distribution of cases at the European Union / European Economic Area level. Two types of datasets can be used: - The default dataset of salmonella 2012-2016 data; - Any dataset specified as described in the vignette.  

# Epidemiological data analysis and modelling

* [SpatialEpi](https://cran.r-project.org/web/packages/SpatialEpi/index.html): Methods and data for cluster detection and disease mapping.  
* [popEpi](https://cran.r-project.org/web/packages/popEpi/index.html): Enables computation of epidemiological statistics, including those where counts or mortality rates of the reference population are used. Currently supported: excess hazard models, rates, mean survival times, relative survival, and standardized incidence and mortality ratios (SIRs/SMRs), all of which can be easily adjusted for by covariates such as age. Fast splitting and aggregation of 'Lexis' objects (from package 'Epi') and other computations achieved using 'data.table'.   
* [episensr](https://cran.r-project.org/web/packages/episensr/index.html): Basic sensitivity analysis of the observed relative risks adjusting for unmeasured confounding and misclassification of the exposure/outcome, or both. It follows the bias analysis methods and examples from the book by Lash T.L, Fox M.P, and Fink A.K. "Applying Quantitative Bias Analysis to Epidemiologic Data", ('Springer', 2009).  
* [EpiModel](https://cran.r-project.org/web/packages/EpiModel/index.html): Tools for simulating mathematical models of infectious disease dynamics. Epidemic model classes include deterministic compartmental models, stochastic individual-contact models, and stochastic network models. Network models use the robust statistical methods of exponential-family random graph models (ERGMs) from the Statnet suite of software packages in R. Standard templates for epidemic modeling include SI, SIR, and SIS disease types. EpiModel features an API for extending these templates to address novel scientific research aims. Full methods for EpiModel are detailed in Jenness et al. (2018, <doi:10.18637/jss.v084.i08>).   
* [mem](https://cran.r-project.org/web/packages/mem/index.html): The Moving Epidemic Method, created by T Vega and JE Lozano (2012, 2015) <doi:10.1111/j.1750-2659.2012.00422.x>, <doi:10.1111/irv.12330>, allows the weekly assessment of the epidemic and intensity status to help in routine respiratory infections surveillance in health systems. Allows the comparison of different epidemic indicators, timing and shape with past epidemics and across different regions or countries with different surveillance systems. Also, it gives a measure of the performance of the method in terms of sensitivity and specificity of the alert week.  
* [EpiILM](https://cran.r-project.org/web/packages/EpiILM/index.html): Provides tools for simulating from discrete-time individual level models for infectious disease data analysis. This epidemic model class contains spatial and contact-network based models with two disease types: Susceptible-Infectious (SI) and Susceptible-Infectious-Removed (SIR).  
* [surveillance](https://cran.r-project.org/web/packages/surveillance/index.html): Statistical methods for the modeling and monitoring of time series of counts, proportions and categorical data, as well as for the modeling of continuous-time point processes of epidemic phenomena. The monitoring methods focus on aberration detection in count data time series from public health surveillance of communicable diseases, but applications could just as well originate from environmetrics, reliability engineering, econometrics, or social sciences. The package implements many typical outbreak detection procedures such as the (improved) Farrington algorithm, or the negative binomial GLR-CUSUM method of Höhle and Paul (2008) <doi:10.1016/j.csda.2008.02.015>. A novel CUSUM approach combining logistic and multinomial logistic modeling is also included. The package contains several real-world data sets, the ability to simulate outbreak data, and to visualize the results of the monitoring in a temporal, spatial or spatio-temporal fashion. A recent overview of the available monitoring procedures is given by Salmon et al. (2016) <doi:10.18637/jss.v070.i10>. For the retrospective analysis of epidemic spread, the package provides three endemic-epidemic modeling frameworks with tools for visualization, likelihood inference, and simulation. hhh4() estimates models for (multivariate) count time series following Paul and Held (2011) <doi:10.1002/sim.4177> and Meyer and Held (2014) <doi:10.1214/14-AOAS743>. twinSIR() models the susceptible-infectious-recovered (SIR) event history of a fixed population, e.g, epidemics across farms or networks, as a multivariate point process as proposed by Höhle (2009) <doi:10.1002/bimj.200900050>. twinstim() estimates self-exciting point process models for a spatio-temporal point pattern of infective events, e.g., time-stamped geo-referenced surveillance data, as proposed by Meyer et al. (2012) <doi:10.1111/j.1541-0420.2011.01684.x>. A recent overview of the implemented space-time modeling frameworks for epidemic phenomena is given by Meyer et al. (2017) <doi:10.18637/jss.v077.i11>.  
* [memapp](https://cran.r-project.org/web/packages/memapp/index.html): The Moving Epidemic Method, created by T Vega and JE Lozano (2012, 2015) <doi:10.1111/j.1750-2659.2012.00422.x>, <doi:10.1111/irv.12330>, allows the weekly assessment of the epidemic and intensity status to help in routine respiratory infections surveillance in health systems. Allows the comparison of different epidemic indicators, timing and shape with past epidemics and across different regions or countries with different surveillance systems. Also, it gives a measure of the performance of the method in terms of sensitivity and specificity of the alert week. 'memapp' is a web application created in the Shiny framework for the 'mem' R package.  
* [epinet](https://cran.r-project.org/web/packages/epinet/index.html): A collection of epidemic/network-related tools. Simulates transmission of diseases through contact networks. Performs Bayesian inference on network and epidemic parameters, given epidemic data.  
* [epimdr](https://cran.r-project.org/web/packages/epimdr/index.html): Functions, data sets and shiny apps for "Epidemics: Models and Data in R" by Ottar N. Bjornstad (ISBN 978-3-319-97487-3) <https://www.springer.com/gp/book/9783319974866>. The package contains functions to study the S(E)IR model, spatial and age-structured SIR models; time-series SIR and chain-binomial stochastic models; catalytic disease models; coupled map lattice models of spatial transmission and network models for social spread of infection. The package is also an advanced quantitative companion to the coursera Epidemics Massive Online Open Course <https://www.coursera.org/learn/epidemics>.    
* [EpiILMCT](https://cran.r-project.org/web/packages/EpiILMCT/index.html): Provides tools for simulating from continuous-time individual level models of disease transmission, and carrying out infectious disease data analyses with the same models. The epidemic models considered are distance-based and/or contact network-based models within Susceptible-Infectious-Removed (SIR) or Susceptible-Infectious-Notified-Removed (SINR) compartmental frameworks. An overview of the implemented continuous-time individual level models for epidemics is given by Almutiry and Deardon (2019) <doi:10.1515/ijb-2017-0092>.  
* [outbreaker2](https://cran.r-project.org/web/packages/outbreaker2/index.html): Bayesian reconstruction of disease outbreaks using epidemiological and genetic information. Jombart T, Cori A, Didelot X, Cauchemez S, Fraser C and Ferguson N. 2014. <doi:10.1371/journal.pcbi.1003457>. Campbell, F, Cori A, Ferguson N, Jombart T. 2019. <doi:10.1371/journal.pcbi.1006930>.  
* [riskCommunicator](https://cran.r-project.org/web/packages/riskCommunicator/index.html): Estimates flexible epidemiological effect measures including both differences and ratios using the parametric G-formula developed as an alternative to inverse probability weighting. It is useful for estimating the impact of interventions in the presence of treatment-confounder-feedback. G-computation was originally described by Robbins (1986) <doi:10.1016/0270-0255(86)90088-6> and has been described in detail by Ahern, Hubbard, and Galea (2009) <doi:10.1093/aje/kwp015>; Snowden, Rose, and Mortimer (2011) <doi:10.1093/aje/kwq472>; and Westreich et al. (2012) <doi:10.1002/sim.5316>.  
* [EpiEstim](https://cran.r-project.org/web/packages/EpiEstim/index.html): Tools to quantify transmissibility throughout an epidemic from the analysis of time series of incidence as described in Cori et al. (2013) <doi:10.1093/aje/kwt133> and Wallinga and Teunis (2004) <doi:10.1093/aje/kwh255>.   
* [R0](https://cran.r-project.org/web/packages/R0/index.html): Estimation of reproduction numbers for disease outbreak, based on incidence data. The R0 package implements several documented methods. It is therefore possible to compare estimations according to the methods used. Depending on the methods requested by user, basic reproduction number (commonly denoted as R0) or real-time reproduction number (referred to as R(t)) is computed, along with a 95% Confidence Interval. Plotting outputs will give different graphs depending on the methods requested : basic reproductive number estimations will only show the epidemic curve (collected data) and an adjusted model, whereas real-time methods will also show the R(t) variations throughout the outbreak time period. Sensitivity analysis tools are also provided, and allow for investigating effects of varying Generation Time distribution or time window on estimates.  
* [EpiContactTrace](https://cran.r-project.org/web/packages/EpiContactTrace/index.html): Routines for epidemiological contact tracing and visualisation of network of contacts.  
* [epicontacts](https://cran.r-project.org/web/packages/epicontacts/index.html): A collection of tools for representing epidemiological contact data, composed of case line lists and contacts between cases. Also contains procedures for data handling, interactive graphics, and statistics.  
* [DSAIDE](https://cran.r-project.org/web/packages/DSAIDE/index.html): Exploration of simulation models (apps) of various infectious disease transmission dynamics scenarios. The purpose of the package is to help individuals learn about infectious disease epidemiology (ecology/evolution) from a dynamical systems perspective. All apps include explanations of the underlying models and instructions on what to do with the models.  
* [nosoi](https://cran.r-project.org/web/packages/nosoi/index.html): The aim of 'nosoi' (pronounced no.si) is to provide a flexible agent-based stochastic transmission chain/epidemic simulator (Lequime et al. bioRxiv 2020.03.03.973107). It is named after the daimones of plague, sickness and disease that escaped Pandora's jar in the Greek mythology. 'nosoi' is able to take into account the influence of multiple variable on the transmission process (e.g. dual-host systems (such as arboviruses), within-host viral dynamics, transportation, population structure), alone or taken together, to create complex but relatively intuitive epidemiological simulations. 
* [argo](https://cran.r-project.org/web/packages/argo/index.html): Augmented Regression with General Online data (ARGO) for accurate estimation of influenza epidemics in United States on both national level and regional level. It replicates the method introduced in paper Yang, S., Santillana, M. and Kou, S.C. (2015) <doi:10.1073/pnas.1515373112> and Ning, S., Yang, S. and Kou, S.C. (2019) <doi:10.1038/s41598-019-41559-6>.  

# COVID-19

* [coronavirus](https://cran.r-project.org/web/packages/coronavirus/index.html): Provides a daily summary of the Coronavirus (COVID-19) cases by state/province. Data source: Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus <https://systems.jhu.edu/research/public-health/ncov/>.     
* [covid19italy](https://cran.r-project.org/web/packages/covid19italy/index.html): Provides a daily summary of the Coronavirus (COVID-19) cases in Italy by country, region and province level. Data source: Presidenza del Consiglio dei Ministri - Dipartimento della Protezione Civile <http://www.protezionecivile.it/>.  
* [COVID19](https://cran.r-project.org/web/packages/COVID19/index.html): Download COVID-19 data across governmental sources at national, regional, and city level, as described in Guidotti and Ardia (2020) <doi:10.21105/joss.02376>. Includes the time series of vaccines, tests, cases, deaths, recovered, hospitalizations, intensive therapy, and policy measures by 'Oxford COVID-19 Government Response Tracker' <https://www.bsg.ox.ac.uk/research/research-projects/coronavirus-government-response-tracker>. Provides a seamless integration with 'World Bank Open Data' <https://data.worldbank.org/>, 'Google Mobility Reports' <https://www.google.com/covid19/mobility/>, 'Apple Mobility Reports' <https://covid19.apple.com/mobility>.   
* [covid19.analytics](https://cran.r-project.org/web/packages/covid19.analytics/index.html): Load and analyze updated time series worldwide data of reported cases for the Novel CoronaVirus Disease (CoViD-19) from the Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE) data repository <https://github.com/CSSEGISandData/COVID-19>. The datasets are available in two main modalities, as a time series sequences and aggregated for the last day with greater spatial resolution. Several analysis, visualization and modelling functions are available in the package that will allow the user to compute and visualize total number of cases, total number of changes and growth rate globally or for an specific geographical location, while at the same time generating models using these trends; generate interactive visualizations and generate Susceptible-Infected-Recovered (SIR) model for the disease spread.    
* [covid19us](https://cran.r-project.org/web/packages/covid19us/index.html): A wrapper around the 'COVID Tracking Project API' <https://covidtracking.com/api/> providing data on cases of COVID-19 in the US.  
* [covid19br](https://cran.r-project.org/web/packages/covid19br/index.html): Set of functions to import COVID-19 pandemic data into R. The Brazilian COVID-19 data, obtained from the official Brazilian repository at <https://covid.saude.gov.br/>, is available at country, region, state, and city-levels. The package also downloads the world-level COVID-19 data from the John Hopkins University's repository.  
* [oxcovid19](https://cran.r-project.org/web/packages/oxcovid19/index.html): The OxCOVID19 Project <https://covid19.eng.ox.ac.uk> aims to increase our understanding of the COVID-19 pandemic and elaborate possible strategies to reduce the impact on the society through the combined power of statistical, mathematical modelling, and machine learning techniques. The OxCOVID19 Database is a large, single-centre, multimodal relational database consisting of information (using acknowledged sources) related to COVID-19 pandemic. This package provides an R-specific interface to the OxCOVID19 Database based on widely-used data handling and manipulation approaches in R.  
* [bets.covid19](https://cran.r-project.org/web/packages/bets.covid19/index.html): Implements likelihood inference for early epidemic analysis. BETS is short for the four key epidemiological events being modeled: Begin of exposure, End of exposure, time of Transmission, and time of Symptom onset. The package contains a dataset of the trajectory of confirmed cases during the coronavirus disease (COVID-19) early outbreak. More detail of the statistical methods can be found in Zhao et al. (2020) <arXiv:2004.07743>.  
* [covid19sf](https://cran.rstudio.com/web/packages/covid19sf/index.html): Provides a verity of summary tables of the Covid19 cases in San Francisco. Data source: San Francisco, Department of Public Health - Population Health Division <https://datasf.org/opendata/>.   
* [covid19mobility](https://cran.r-project.org/web/packages/covid19mobility/index.html): Scrapes trends in mobility after the Covid-19 outbreak from different sources. Currently, the package scrapes data from Google <https://www.google.com/covid19/mobility/>, Apple <https://www.apple.com/covid19/mobility>, and will add others. The data returned uses the tidy Covid19R project data standard <https://covid19r.github.io/documentation/> as well as the controlled vocabularies for measurement types.  
* [covid19nytimes](https://cran.r-project.org/web/packages/covid19nytimes/index.html): Accesses the NY Times Covid-19 county-level data for the US, described in <https://www.nytimes.com/article/coronavirus-county-data-us.html> and available at <https://github.com/nytimes/covid-19-data>. It then returns the data in a tidy data format according to the Covid19R Project data specification. If you plan to use the data or publicly display the data or results, please make sure cite the original NY Times source. Please read and follow the terms laid out in the data license at <https://github.com/nytimes/covid-19-data/blob/master/LICENSE>.  
* [covid19france](https://cran.r-project.org/web/packages/covid19france/index.html): Imports and cleans 'opencovid19-fr' <https://github.com/opencovid19-fr/data> data on COVID-19 in France.  
* [covid19dbcand](https://cran.r-project.org/web/packages/covid19dbcand/index.html): Provides different datasets parsed from 'Drugbank' <https://www.drugbank.ca/covid-19> database using 'dbparser' package. It is a smaller version from 'dbdataset' package. It contains only information about COVID-19 possible treatment.  
* [covid19swiss](https://cran.r-project.org/web/packages/covid19swiss/index.html): Provides a daily summary of the Coronavirus (COVID-19) cases in Switzerland cantons and Principality of Liechtenstein. Data source: Specialist Unit for Open Government Data Canton of Zurich <https://www.zh.ch/de/politik-staat/opendata.html>.  
* [corona](https://cran.r-project.org/web/packages/corona/index.html): Manipulate and view coronavirus data and other societally relevant data at a basic level.  
* [CovidMutations](https://cran.r-project.org/web/packages/CovidMutations/index.html): A feasible framework for mutation analysis and reverse transcription polymerase chain reaction (RT-PCR) assay evaluation of COVID-19, including mutation profile visualization, statistics and mutation ratio of each assay. The mutation ratio is conducive to evaluating the coverage of RT-PCR assays in large-sized samples. Mercatelli, D. and Giorgi, F. M. (2020) <doi:10.20944/preprints202004.0529.v1>.  
* [oxcgrt](https://cran.r-project.org/web/packages/oxcgrt/index.html): The Oxford COVID-19 Government Response Tracker (OxCGRT) tracks and compares worldwide government responses to the COVID-19 pandemic rigorously and consistently. OxCGRT makes available systematic information in a consistent way, aiding those who require information have access to it efficiently for their purposes. This package facilitates access to the OxCGRT data via its API <https://covidtracker.bsg.ox.ac.uk/> and includes functions to calculate the various OxCGRT indices in R.  

# Related links

* R Epidemics Cpnsortium (RECON), non-profit organisation developing professional tools in for field epidemiologists: repidemicsconsortium.org/projects/
* RECON's task manager, issues regarding RECON packages + partners: tasks.repidemicsconsortium.org
* Multivariate statistics task view: cran.r-project.org/web/views/Multivariate.html
* Survival analysis task view: cran.r-project.org/web/views/Survival.html
* Data visualisation and graphics task view: cran.r-project.org/web/views/Graphics.html

