---
title: "RECON COVID-19 challenge"
subtitle: "Project log"
date: "last modified `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(DiagrammeR)
library(pander)
```

## Useful links

[Project repo](https://github.com/matthieugold/covid19_challenge)

[Link to Trello](https://trello.com/b/PQch7ney/covid19-challenge)

[Link to Slack](https://app.slack.com/client/T2SFJJQRL/G016PGWRPAA/thread/C2SFJJV8E-1594388640.056600)

[Documents created by Matthieu](https://matthieugold.github.io/covid-19-challenge/docs/document_list.html)

## Time line

```{r out.width = "100%", fig.height = 3}
DiagrammeR::mermaid("
gantt
dateFormat  YYYY-MM-DD
title RECON COVID-19 CHALLENGE TIMELINE

section Milestones
1. setup                      :done,          overall_1,   2020-07-10, 1d
2. early stage assessment     :active         overall_2,  after overall_1, 2020-08-07   
3. initial release            :               overall_3,  2020-08-08, 2020-08-30
4. mid-stage assessment       :               overall_4,  after overall_3, 2020-09-27
5. second release             :               overall_5,  after overall_4, 2020-10-10
6. task view epidemics        :               overall_6,  after overall_5, 2020-10-25
7. final assessment           :               overall_7,  after overall_6, 2020-11-27

section Matthieu

section Benjamin
")
```

## Log

2020-07-10: [Launch meeting](meeting_notes/2020-07-10_launch_meeting.html)  
2020-07-17: [Meeting](meeting_notes/2020-07-17_meeting.html)

