---
title: "questions for thibaut"
author: "M. Rolland"
date: "17/07/2020"
output: html_document
---

# Recon

Recon – lifecycle
  
* where did recon come from?
  * origine hackathon epi/stat hackout at berkeley avec Ropensci (K. Ram)
  * idée de promouvoir l'open source pour la epidemic response
  * reseau epiet etc
  * 2018 creation de l'asso
* Where is it now? 
  * message structuré
  * rassembler la communauté avec des profils différents epi, stats, modellers, devs, etc
  * stt ebola et covid
  * 3 piliers
    * dev logiciels
    * training
    * deployment, apporter du soutien sur le terrain
* Where is it going? what are recon’s ambitions?
  * promouvoir les outils pour les situations d'urgence humanitaire
  * etre utile
  * etre mieux préparé a l'analyse en situation d'uregnce humanitaire
  * vision idéale: reconverse (epi, humanitaire), avec un réseau, développer la communauté
  * créer la vommunauté

Recon development

* who are the main developers?
* how are the development decisions made? Prioritised?
  * organic process
* what are the current major developments?
  * no strategy so far
  * may change
  * see how the different packages are associated

Recon in use

* who are recon users?
  * low income
  * gouverment espagnol utilise incidence
  * OMS epicontact
* how much is recon used? What is the dynamic?
  * augmentation (suivie de manière qualtative: nb de followers twitter, )
* are some packages more used than others?
* is there any recon tutorial? Training? How is it taught?
  * recon learn, check les tutos
  * r4epi, Recon + MSF: fait des templates pour des surveys, outbreaks response
* is recon self sufficient to deal with an outbreak?
  * NON (pas au niveau humain) 
  * il y a plus de gens recon qui savent faire de l'analyse que l'OMS
  * packages recon complémentaires de ce qui existe déjà 
  * ca sera jamais que Recon 
* how to Recon members and Recon users communicate outside the slack? How mush is the Slack used? How much of the Recon users are on the slack?
  * OUI
  * mailing list

# Task manager

* need to talk about the task lifecycle (cf doc: https://docs.google.com/document/d/1nJ-3z9_Sjt1H5QObYqcCJwlX12t9PWyj6JVMF-_GljE/edit)
* Who will authorise the new tasks? Manually? Automatic?
* Platform/domain name?
  * faire une plateforme générale
  * dire qu'en priorité on fait du covid-19
* Data base? AWS, Rstudio? (see 17/07 notes)
  * demander plus de détails à Ben => définir les besoins, etre GDPR compatible
* Who will write the platform content? (about, help, etc.) see doc
  * me draft then others edit
* OK to connect with github credentials?

# Other

* Is the cran view an infectious disease epi or general epi (including environmental) or just field epi?
  * Infectious epi
* who to/how/when do I bill my hours?
  * invoice for r consortium
