---
title: "Website specs"
author: "M. Rolland"
date: "10/07/2020"
output: 
  html_document:
    toc: true
    number_sections: true
---

# Job offer specs

static website; may use free and / or open-source content management systems (CMS)

* sources of the website should use version control and be hosted on a public repository (ideally git/github)
* provide a user-friendly interface listing existing R-tasks reflecting analytics needs for the response to COVID-19, each task pointing to a github issue; for a (more complex) example, see https://tasks.hotosm.org/explore
* provide a streamlined way (e.g. through google forms) to submit new tasks from existing github issues
* provide a streamlined way (e.g. through google forms) to submit new tasks without existing github issue, creating a new github issue on a dedicated repository on github.com/reconhub
* provide a streamlined way to validate and curate tasks before publishing
* implement priority grading system for tasks
* implement difficulty grading system for tasks
* implement labeling system for tasks
* implement a search engine for tasks
* implement filters for searching tasks
* possibility to vote up and down

# Link with github

* Should all users have a github account?
* Should we ask for authorisation to pull github info? (profile pic etc?)

# Site map

## Home page

* about
* learn
* explore projects
* link to personnal profile page
* my contributions

## About

About the Recon task managing project

## Learn

Tutorials on how to submit a task, and how to contribute to a task
  
## Personnal profile page

* see pic, name, level
* edit personnal info
  * pic
  * full name
* ask for personnal interests? (R-wise)
* different levels of notifications

# Other

Ideas:

* Mobile compatible
* automatic request notification? (twitter? email for those who wish? etc)
* badge system to reward users? (low priority)

Questions

* how will users assigned to a given task be informed of any new activity regarding that task (the person who opened it and the persion who took it on)
* database
* authorisations for tasks
* 
